In [1]:
print("Hello world!")

Hello world!


In [3]:
import numpy as np

In [5]:
myPythonList = [1,9,8,3]
print(myPythonList)

[1, 9, 8, 3]


In [8]:
numpy_array_from_list = np.array(myPythonList)
numpy_array_from_list

array([1, 9, 8, 3])

In [10]:
a  = np.array([1,9,8,3])
print(a)

[1 9 8 3]


In [12]:
x=numpy_array_from_list + 125
print(x)

[126 134 133 128]


In [14]:
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int32


In [16]:
b  = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


In [18]:
c = np.array([(1,2,3),
              (4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


In [20]:
import numpy as np
x=np.zeros((2,2), dtype=np.int16)
print(x)

[[0 0]
 [0 0]]


In [22]:
import numpy as np
np.ones((1,2,3), dtype=np.int16)

array([[[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [24]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
e.flatten()


array([1, 2, 3, 4, 5, 6])

In [28]:
ran_num_array = np.random.normal(5, 0.5, 10)
print(ran_num_array)

[4.40025436 5.46125441 4.90917329 5.17128863 5.06200077 5.47069404
 4.75764663 5.99992621 5.31635399 4.38330669]


In [30]:
A = np.matrix(np.ones((4,4)))
np.array(A)[2]=2 
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [34]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
np.arange(0, 35, 7)

array([ 0,  7, 14, 21, 28])

In [38]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)

[[1 2 3]
 [4 5 6]]


In [40]:
print('First row:', e[0])
print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In [42]:
f = np.array([1,2])
g = np.array([4,5])
np.dot(f, g)

14

In [44]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [46]:
gfg = np.matrix('[6, 2; 3, 4]')
diag = gfg.diagonal()
   
print(diag)

[[6 4]]


In [47]:
gfg = np.matrix('[4, 1; 12, 3]')
tracem = gfg.trace()
    
print(tracem)

[[7]]
